In [1]:
import os
import tensorflow as tf
from tfx.components import CsvExampleGen
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
#from tfx.utils.dsl_utils import external_input

## Ingesting Local Data Files

In [2]:
#from tfx.utils.dsl_utils import external_input

base_dir = os.getcwd()
input_dir = os.path.join(base_dir, 'data')
#file_path = f'{input_dir}\\housing.csv'
context= InteractiveContext()
example_gen = CsvExampleGen(input_base='data/csv')
context.run(example_gen)

ExecutionResult(
    component_id: CsvExampleGen
    execution_id: 1
    outputs:
        examples: Channel(
            type_name: Examples
            artifacts: [Artifact(artifact: id: 1
        type_id: 14
        uri: "C:\\Users\\vk006\\AppData\\Local\\Temp\\tfx-interactive-2022-02-15T17_30_07.102016-o33bl8z7\\CsvExampleGen\\examples\\1"
        properties {
          key: "split_names"
          value {
            string_value: "[\"train\", \"eval\"]"
          }
        }
        custom_properties {
          key: "file_format"
          value {
            string_value: "tfrecords_gzip"
          }
        }
        custom_properties {
          key: "input_fingerprint"
          value {
            string_value: "split:single_split,num_files:1,total_bytes:1423529,xor_checksum:1644591257,sum_checksum:1644591257"
          }
        }
        custom_properties {
          key: "payload_format"
          value {
            string_value: "FORMAT_TF_EXAMPLE"
          }
        }
        custom_properties {
          key: "span"
          value {
            int_value: 0
          }
        }
        custom_properties {
          key: "state"
          value {
            string_value: "published"
          }
        }
        custom_properties {
          key: "tfx_version"
          value {
            string_value: "1.6.0"
          }
        }
        state: LIVE
        , artifact_type: id: 14
        name: "Examples"
        properties {
          key: "span"
          value: INT
        }
        properties {
          key: "split_names"
          value: STRING
        }
        properties {
          key: "version"
          value: INT
        }
        base_type: DATASET
        )]
            additional_properties: {}
            additional_custom_properties: {}
        ))

## Splitting Datasets

In [3]:
from tfx.proto import example_gen_pb2

context= InteractiveContext()
base_dir = os.getcwd()
data_dir = os.path.join(os.pardir, "data", "csv")
output = example_gen_pb2.Output(split_config=example_gen_pb2.SplitConfig(splits=[
    example_gen_pb2.SplitConfig.Split(name='train', hash_buckets=6),
    example_gen_pb2.SplitConfig.Split(name='eval', hash_buckets=2),
    example_gen_pb2.SplitConfig.Split(name='test', hash_buckets=2)]
))

input = example_gen_pb2.Input(splits=[
    example_gen_pb2.Input.Split(name='train', pattern='train/*'),
    example_gen_pb2.Input.Split(name='eval', pattern='eval/*'),
    example_gen_pb2.Input.Split(name='test', pattern='test/*')
])

example_gen = CsvExampleGen(input_base='data/csv', output_config=output)
context.run(example_gen)

ExecutionResult(
    component_id: CsvExampleGen
    execution_id: 1
    outputs:
        examples: Channel(
            type_name: Examples
            artifacts: [Artifact(artifact: id: 1
        type_id: 14
        uri: "C:\\Users\\vk006\\AppData\\Local\\Temp\\tfx-interactive-2022-02-15T17_30_24.273908-xl_k65ep\\CsvExampleGen\\examples\\1"
        properties {
          key: "split_names"
          value {
            string_value: "[\"train\", \"eval\", \"test\"]"
          }
        }
        custom_properties {
          key: "file_format"
          value {
            string_value: "tfrecords_gzip"
          }
        }
        custom_properties {
          key: "input_fingerprint"
          value {
            string_value: "split:single_split,num_files:1,total_bytes:1423529,xor_checksum:1644591257,sum_checksum:1644591257"
          }
        }
        custom_properties {
          key: "payload_format"
          value {
            string_value: "FORMAT_TF_EXAMPLE"
          }
        }
        custom_properties {
          key: "span"
          value {
            int_value: 0
          }
        }
        custom_properties {
          key: "state"
          value {
            string_value: "published"
          }
        }
        custom_properties {
          key: "tfx_version"
          value {
            string_value: "1.6.0"
          }
        }
        state: LIVE
        , artifact_type: id: 14
        name: "Examples"
        properties {
          key: "span"
          value: INT
        }
        properties {
          key: "split_names"
          value: STRING
        }
        properties {
          key: "version"
          value: INT
        }
        base_type: DATASET
        )]
            additional_properties: {}
            additional_custom_properties: {}
        ))

In [4]:
example_gen.outputs['examples'].get()

[Artifact(artifact: id: 1
 type_id: 14
 uri: "C:\\Users\\vk006\\AppData\\Local\\Temp\\tfx-interactive-2022-02-15T17_30_24.273908-xl_k65ep\\CsvExampleGen\\examples\\1"
 properties {
   key: "split_names"
   value {
     string_value: "[\"train\", \"eval\", \"test\"]"
   }
 }
 custom_properties {
   key: "file_format"
   value {
     string_value: "tfrecords_gzip"
   }
 }
 custom_properties {
   key: "input_fingerprint"
   value {
     string_value: "split:single_split,num_files:1,total_bytes:1423529,xor_checksum:1644591257,sum_checksum:1644591257"
   }
 }
 custom_properties {
   key: "payload_format"
   value {
     string_value: "FORMAT_TF_EXAMPLE"
   }
 }
 custom_properties {
   key: "span"
   value {
     int_value: 0
   }
 }
 custom_properties {
   key: "state"
   value {
     string_value: "published"
   }
 }
 custom_properties {
   key: "tfx_version"
   value {
     string_value: "1.6.0"
   }
 }
 state: LIVE
 , artifact_type: id: 14
 name: "Examples"
 properties {
   key: "span"
 

In [5]:
for artifact in example_gen.outputs['examples'].get():
    print(artifact)

Artifact(artifact: id: 1
type_id: 14
uri: "C:\\Users\\vk006\\AppData\\Local\\Temp\\tfx-interactive-2022-02-15T17_30_24.273908-xl_k65ep\\CsvExampleGen\\examples\\1"
properties {
  key: "split_names"
  value {
    string_value: "[\"train\", \"eval\", \"test\"]"
  }
}
custom_properties {
  key: "file_format"
  value {
    string_value: "tfrecords_gzip"
  }
}
custom_properties {
  key: "input_fingerprint"
  value {
    string_value: "split:single_split,num_files:1,total_bytes:1423529,xor_checksum:1644591257,sum_checksum:1644591257"
  }
}
custom_properties {
  key: "payload_format"
  value {
    string_value: "FORMAT_TF_EXAMPLE"
  }
}
custom_properties {
  key: "span"
  value {
    int_value: 0
  }
}
custom_properties {
  key: "state"
  value {
    string_value: "published"
  }
}
custom_properties {
  key: "tfx_version"
  value {
    string_value: "1.6.0"
  }
}
state: LIVE
, artifact_type: id: 14
name: "Examples"
properties {
  key: "span"
  value: INT
}
properties {
  key: "split_names"
  

### Text file processing using Apache Beam

In [ ]:
import re

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions


input_file = "data/kinglear.txt"
output_file = "output.txt"

pipeline_options = PipelineOptions()


with beam.Pipeline(options=pipeline_options) as p: 

    # Read the text file[pattern] into a PCollection.
    lines = p | beam.io.ReadFromText(input_file)

    # Count the occurrences of each word.
    counts = (
        lines
        | 'Split' >> (beam.FlatMap(lambda x: re.findall(r'[A-Za-z\']+', x)))
                      # .with_output_types(unicode))
        | 'PairWithOne' >> beam.Map(lambda x: (x, 1))
        | 'GroupAndSum' >> beam.CombinePerKey(sum))

    # Format the counts into a PCollection of strings.
    def format_result(word_count):
        (word, count) = word_count
        return f"{word}: {count}"

    output = counts | 'Format' >> beam.Map(format_result)

    # Write the output using a "Write" transform that has side effects.
    output | beam.io.WriteToText(output_file)

### TF Records

In [7]:
# Write TF records
with tf.io.TFRecordWriter("test.tfrecord") as w:
    w.write(b"First record")
    w.write(b"Second record")

# Read TF records
for record in tf.data.TFRecordDataset("test.tfrecord"):
    print(record)

tf.Tensor(b'First record', shape=(), dtype=string)
tf.Tensor(b'Second record', shape=(), dtype=string)


In [12]:
import csv

import tensorflow as tf
from tqdm import tqdm

def _byte_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def clean_rows(row):
    if not row['ZIP code']:
        row['ZIP code'] = '99999'

    return row

def convert_zipcode_to_int(zipcode):
    if isinstance(zipcode, str) and "XX" in zipcode:
        zipcode = zipcode.replace("XX", "00")
    int_zipcode = int(zipcode)
    return int_zipcode

original_file_path = "data/csv/housing.csv"
tfrecords_filename = "housing.tfrecords"
tf_record_writer = tf.io.TFRecordWriter(tfrecords_filename)

In [13]:
# feature={
#                     "product": _byte_feature(row['Product'].encode('utf-8')),
#                     "sub_product": _byte_feature(row['Sub-product'].encode('utf-8')),
#                     "issue": _byte_feature(row['Issue'].encode('utf-8')),
#                     "sub_issue": _byte_feature(row['Sub-issue'].encode('utf-8')),
#                     "state": _byte_feature(row['State'].encode('utf-8')),
#                     "zip_code": _int64_feature(convert_zipcode_to_int(row['ZIP code'])),
#                     "company_response": _byte_feature(row['Company public response'].encode('utf-8')),
#                     "company": _byte_feature(row['Company'].encode('utf-8')),
#                     "timely_response": _byte_feature(row["Timely response?"].encode('utf-8')),
#                     "consumer_disputed": _byte_feature(row["Consumer disputed?"].encode('utf-8')),
#                     "tag": _byte_feature(row['Tags'].encode('utf-8'))

#                 }

In [14]:
def clean_bed_room(bed_rooms):
    if isinstance(bed_rooms, str) and "" in bed_rooms:
         return 0        

    return bed_rooms


In [15]:
with open(original_file_path) as csv_file:
    reader = csv.DictReader(csv_file, delimiter=',', quotechar='"')
    for row in tqdm(reader):
        #row = clean_rows(row)
        example = tf.train.Example(
            features=tf.train.Features(
                feature = {
                    "housing_age": _float_feature(float(row['housing_median_age'].encode('utf-8'))),
                    "total_rooms": _float_feature(float(row['total_rooms'].encode('utf-8'))),
                    "total_bedrooms": _float_feature(float(clean_bed_room(row['total_bedrooms']))),
                    "population": _float_feature(float(row['population'].encode('utf-8'))),
                    "households": _float_feature(float(row['households'].encode('utf-8'))),
                    "median_income": _float_feature(float(row['median_income'].encode('utf-8'))),
                    "median_house_value": _float_feature(float(row['median_house_value'].encode('utf-8'))),
                    "ocean_proximity": _byte_feature(row['ocean_proximity'].encode('utf-8'))

                }
            )
        )
        tf_record_writer.write(example.SerializeToString())

tf_record_writer.close()

20640it [00:02, 9591.82it/s]


In [16]:
# Create a description of the features.
feature_description = {
    'housing_age': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
    'total_rooms': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
    'total_bedrooms': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
    'population': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
    'households': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
    'median_income': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
    'median_house_value': tf.io.FixedLenFeature([], tf.float32, default_value=0.0),
    'ocean_proximity': tf.io.FixedLenFeature([], tf.string, default_value=''),
    
}

def _parse_function(example_proto):
    # Parse the input `tf.train.Example` proto using the dictionary above.
    return tf.io.parse_single_example(example_proto, feature_description)

In [17]:
raw_dataset = tf.data.TFRecordDataset(tfrecords_filename)
parsed_dataset = raw_dataset.map(_parse_function)
for record in parsed_dataset.take(10):
    print(repr(record))

{'households': <tf.Tensor: shape=(), dtype=float32, numpy=126.0>, 'housing_age': <tf.Tensor: shape=(), dtype=float32, numpy=41.0>, 'median_house_value': <tf.Tensor: shape=(), dtype=float32, numpy=452600.0>, 'median_income': <tf.Tensor: shape=(), dtype=float32, numpy=8.3252>, 'ocean_proximity': <tf.Tensor: shape=(), dtype=string, numpy=b'NEAR BAY'>, 'population': <tf.Tensor: shape=(), dtype=float32, numpy=322.0>, 'total_bedrooms': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, 'total_rooms': <tf.Tensor: shape=(), dtype=float32, numpy=880.0>}
{'households': <tf.Tensor: shape=(), dtype=float32, numpy=1138.0>, 'housing_age': <tf.Tensor: shape=(), dtype=float32, numpy=21.0>, 'median_house_value': <tf.Tensor: shape=(), dtype=float32, numpy=358500.0>, 'median_income': <tf.Tensor: shape=(), dtype=float32, numpy=8.3014>, 'ocean_proximity': <tf.Tensor: shape=(), dtype=string, numpy=b'NEAR BAY'>, 'population': <tf.Tensor: shape=(), dtype=float32, numpy=2401.0>, 'total_bedrooms': <tf.Tensor: sha

### TF data validation

In [18]:
import tensorflow_data_validation as tfdv
stats = tfdv.generate_statistics_from_tfrecord(data_location=tfrecords_filename)

Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


### Generating Schema from Your Data

In [19]:
schema = tfdv.infer_schema(stats)

In [20]:
tfdv.display_schema(schema)

Type  Presence Valency             Domain
Feature name                                                     
'households'           FLOAT  required                          -
'housing_age'          FLOAT  required                          -
'median_house_value'   FLOAT  required                          -
'median_income'        FLOAT  required                          -
'ocean_proximity'     STRING  required          'ocean_proximity'
'population'           FLOAT  required                          -
'total_bedrooms'       FLOAT  required                          -
'total_rooms'          FLOAT  required                          -

Values
Domain                                                                      
'ocean_proximity'  '<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'

In [21]:
tfdv.visualize_statistics(lhs_statistics=stats, rhs_statistics=stats,lhs_name='VAL_DATASET', rhs_name='TRAIN_DATASET')

## Anomalies

In [22]:
anomalies = tfdv.validate_statistics(statistics=stats, schema=schema)
tfdv.display_anomalies(anomalies)